# Generated by Django 3.2.8 on 2021-10-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_name', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=20)),
            ],
        ),
    ]
